<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-SeaVersion_2_20170818051512" Class="SeaModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\db\aspnet-SeaVersion_2_20170818051512.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="LinqPractice.Properties.Settings" SettingsPropertyName="aspnet_SeaVersion_2_20170818051512ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[__MigrationHistory]" Member="__MigrationHistories">
    <Type Name="__MigrationHistory">
      <Column Name="MigrationId" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContextKey" Type="System.String" DbType="NVarChar(300) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProductVersion" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetVirtualRole" Member="AspNetVirtualRoles">
    <Type Name="AspNetVirtualRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="AspNetVirtualRole_AspNetVirtualRole" Member="AspNetVirtualRole2" ThisKey="Id" OtherKey="Id" Type="AspNetVirtualRole" Cardinality="One" />
      <Association Name="AspNetVirtualRole_AspNetVirtualRole" Member="AspNetVirtualRole1" ThisKey="Id" OtherKey="Id" Type="AspNetVirtualRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetAccountants" Member="AspNetAccountants">
    <Type Name="AspNetAccountant">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AspNetEmployee_AspNetAccountant" Member="AspNetEmployee" ThisKey="EmployeeId" OtherKey="Id" Type="AspNetEmployee" IsForeignKey="true" />
      <Association Name="AspNetUser_AspNetAccountant" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetAssessment" Member="AspNetAssessments">
    <Type Name="AspNetAssessment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AssessmentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Attachment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TermId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weightage" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostingDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AspNetAssessment_AspNetStudentAssessment" Member="AspNetStudentAssessments" ThisKey="Id" OtherKey="AssessmentId" Type="AspNetStudentAssessment" />
      <Association Name="AspNetAssessmentType_AspNetAssessment" Member="AspNetAssessmentType" ThisKey="AssessmentTypeId" OtherKey="Id" Type="AspNetAssessmentType" IsForeignKey="true" />
      <Association Name="AspNetTerm_AspNetAssessment" Member="AspNetTerm" ThisKey="TermId" OtherKey="Id" Type="AspNetTerm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetAssessmentTypes" Member="AspNetAssessmentTypes">
    <Type Name="AspNetAssessmentType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetAssessmentType_AspNetAssessment" Member="AspNetAssessments" ThisKey="Id" OtherKey="AssessmentTypeId" Type="AspNetAssessment" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetBranch_Admins" Member="AspNetBranch_Admins">
    <Type Name="AspNetBranch_Admin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AspNetBranch_AspNetBranch_Admin" Member="AspNetBranch" ThisKey="BranchId" OtherKey="Id" Type="AspNetBranch" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetBranch_Admin" Member="AspNetUser" ThisKey="AdminId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetBranch_Class" Member="AspNetBranch_Classes">
    <Type Name="AspNetBranch_Class">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AspNetBranch_Class_AspNetBranchClass_Section" Member="AspNetBranchClass_Sections" ThisKey="Id" OtherKey="BranchClassId" Type="AspNetBranchClass_Section" />
      <Association Name="AspNetBranch_AspNetBranch_Class" Member="AspNetBranch" ThisKey="BranchId" OtherKey="Id" Type="AspNetBranch" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetClass_AspNetBranch_Class" Member="AspNetClass" ThisKey="ClassId" OtherKey="Id" Type="AspNetClass" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetSession_AspNetBranch_Class" Member="AspNetSession" ThisKey="SessionId" OtherKey="Id" Type="AspNetSession" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetBranchClass_Sections" Member="AspNetBranchClass_Sections">
    <Type Name="AspNetBranchClass_Section">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BranchClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AspNetBranchClass_Section_AspNetStudent_Enrollment" Member="AspNetStudent_Enrollments" ThisKey="Id" OtherKey="SectionId" Type="AspNetStudent_Enrollment" />
      <Association Name="AspNetBranchClass_Section_AspNetStudent_History" Member="AspNetStudent_Histories" ThisKey="Id" OtherKey="SectionId" Type="AspNetStudent_History" />
      <Association Name="AspNetBranchClass_Section_AspNetStudentSection" Member="AspNetStudentSections" ThisKey="Id" OtherKey="BranchClassSectionId" Type="AspNetStudentSection" />
      <Association Name="AspNetBranchClass_Section_AspNetTeacher_Enrollment" Member="AspNetTeacher_Enrollments" ThisKey="Id" OtherKey="SectionId" Type="AspNetTeacher_Enrollment" />
      <Association Name="AspNetBranchClass_Section_AspNetTeacher_History" Member="AspNetTeacher_Histories" ThisKey="Id" OtherKey="SectionId" Type="AspNetTeacher_History" />
      <Association Name="AspNetBranch_Class_AspNetBranchClass_Section" Member="AspNetBranch_Class" ThisKey="BranchClassId" OtherKey="Id" Type="AspNetBranch_Class" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetSection_AspNetBranchClass_Section" Member="AspNetSection" ThisKey="SectionId" OtherKey="Id" Type="AspNetSection" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetBranches" Member="AspNetBranches">
    <Type Name="AspNetBranch">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchPrincipalId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Association Name="AspNetBranch_AspNetBranch_Admin" Member="AspNetBranch_Admins" ThisKey="Id" OtherKey="BranchId" Type="AspNetBranch_Admin" />
      <Association Name="AspNetBranch_AspNetBranch_Class" Member="AspNetBranch_Classes" ThisKey="Id" OtherKey="BranchId" Type="AspNetBranch_Class" />
      <Association Name="AspNetBranch_AspNetEmployee" Member="AspNetEmployees" ThisKey="Id" OtherKey="BranchId" Type="AspNetEmployee" />
      <Association Name="AspNetBranch_AspNetStudent" Member="AspNetStudents" ThisKey="Id" OtherKey="BranchId" Type="AspNetStudent" />
      <Association Name="AspNetUser_AspNetBranch" Member="AspNetUser" ThisKey="BranchPrincipalId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetClass_Courses" Member="AspNetClass_Courses">
    <Type Name="AspNetClass_Course">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsMandatory" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AspNetClass_AspNetClass_Course" Member="AspNetClass" ThisKey="ClassId" OtherKey="Id" Type="AspNetClass" IsForeignKey="true" />
      <Association Name="AspNetCourse_AspNetClass_Course" Member="AspNetCourse" ThisKey="CourseId" OtherKey="Id" Type="AspNetCourse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetClasses" Member="AspNetClasses">
    <Type Name="AspNetClass">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NextClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AspNetClass_AspNetBranch_Class" Member="AspNetBranch_Classes" ThisKey="Id" OtherKey="ClassId" Type="AspNetBranch_Class" />
      <Association Name="AspNetClass_AspNetClass_Course" Member="AspNetClass_Courses" ThisKey="Id" OtherKey="ClassId" Type="AspNetClass_Course" />
      <Association Name="AspNetClass_AspNetClass" Member="AspNetClasses" ThisKey="Id" OtherKey="NextClassId" Type="AspNetClass" />
      <Association Name="AspNetClass_AspNetClass" Member="AspNetClass1" ThisKey="NextClassId" OtherKey="Id" Type="AspNetClass" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetCoursePackages" Member="AspNetCoursePackages">
    <Type Name="AspNetCoursePackage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PackageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AspNetCourse_AspNetCoursePackage" Member="AspNetCourse" ThisKey="CourseId" OtherKey="Id" Type="AspNetCourse" IsForeignKey="true" />
      <Association Name="AspNetPackage_AspNetCoursePackage" Member="AspNetPackage" ThisKey="PackageId" OtherKey="Id" Type="AspNetPackage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetCourses" Member="AspNetCourses">
    <Type Name="AspNetCourse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AspNetCourse_AspNetClass_Course" Member="AspNetClass_Courses" ThisKey="Id" OtherKey="CourseId" Type="AspNetClass_Course" />
      <Association Name="AspNetCourse_AspNetCoursePackage" Member="AspNetCoursePackages" ThisKey="Id" OtherKey="CourseId" Type="AspNetCoursePackage" />
      <Association Name="AspNetCourse_AspNetStudent_Enrollment" Member="AspNetStudent_Enrollments" ThisKey="Id" OtherKey="CourseId" Type="AspNetStudent_Enrollment" />
      <Association Name="AspNetCourse_AspNetStudent_History" Member="AspNetStudent_Histories" ThisKey="Id" OtherKey="CourseId" Type="AspNetStudent_History" />
      <Association Name="AspNetCourse_AspNetTeacher_Enrollment" Member="AspNetTeacher_Enrollments" ThisKey="Id" OtherKey="CourseId" Type="AspNetTeacher_Enrollment" />
      <Association Name="AspNetCourse_AspNetTeacher_History" Member="AspNetTeacher_Histories" ThisKey="Id" OtherKey="CourseId" Type="AspNetTeacher_History" />
      <Association Name="AspNetDepartment_AspNetCourse" Member="AspNetDepartment" ThisKey="DepartmentId" OtherKey="Id" Type="AspNetDepartment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetDepartments" Member="AspNetDepartments">
    <Type Name="AspNetDepartment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="HeadId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AspNetDepartment_AspNetCourse" Member="AspNetCourses" ThisKey="Id" OtherKey="DepartmentId" Type="AspNetCourse" />
      <Association Name="AspNetUser_AspNetDepartment" Member="AspNetUser" ThisKey="HeadId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetEmployee" Member="AspNetEmployees">
    <Type Name="AspNetEmployee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAvailable" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NationalityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReligionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GenderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CellNo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Landline" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpouseName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpouseHighestDegree" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SpouseOccupation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GrossSalary" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="BasicSalary" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="MedicalAllowance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Accomodation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProvidedFund" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Tax" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="EOP" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="JoiningDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Illness" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[Spouse Address]" Member="Spouse_Address" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[File]" Member="File" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="AspNetEmployee_AspNetAccountant" Member="AspNetAccountants" ThisKey="Id" OtherKey="EmployeeId" Type="AspNetAccountant" />
      <Association Name="AspNetEmployee_AspNetTeacher" Member="AspNetTeachers" ThisKey="Id" OtherKey="EmployeeId" Type="AspNetTeacher" />
      <Association Name="AspNetBranch_AspNetEmployee" Member="AspNetBranch" ThisKey="BranchId" OtherKey="Id" Type="AspNetBranch" IsForeignKey="true" />
      <Association Name="AspNetEmployeePosition_AspNetEmployee" Member="AspNetEmployeePosition" ThisKey="Position" OtherKey="Id" Type="AspNetEmployeePosition" IsForeignKey="true" />
      <Association Name="AspNetGender_AspNetEmployee" Member="AspNetGender" ThisKey="GenderId" OtherKey="Id" Type="AspNetGender" IsForeignKey="true" />
      <Association Name="AspNetNationality_AspNetEmployee" Member="AspNetNationality" ThisKey="NationalityId" OtherKey="Id" Type="AspNetNationality" IsForeignKey="true" />
      <Association Name="AspNetReligion_AspNetEmployee" Member="AspNetReligion" ThisKey="ReligionId" OtherKey="Id" Type="AspNetReligion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetEmployeePositions" Member="AspNetEmployeePositions">
    <Type Name="AspNetEmployeePosition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PositionName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetEmployeePosition_AspNetEmployee" Member="AspNetEmployees" ThisKey="Id" OtherKey="Position" Type="AspNetEmployee" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetGenders" Member="AspNetGenders">
    <Type Name="AspNetGender">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetGender_AspNetEmployee" Member="AspNetEmployees" ThisKey="Id" OtherKey="GenderId" Type="AspNetEmployee" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetLogs" Member="AspNetLogs">
    <Type Name="AspNetLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Operation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OperationStartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="OperationEndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetLog" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetNationalities" Member="AspNetNationalities">
    <Type Name="AspNetNationality">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetNationality_AspNetEmployee" Member="AspNetEmployees" ThisKey="Id" OtherKey="NationalityId" Type="AspNetEmployee" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetPackages" Member="AspNetPackages">
    <Type Name="AspNetPackage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetPackage_AspNetCoursePackage" Member="AspNetCoursePackages" ThisKey="Id" OtherKey="PackageId" Type="AspNetCoursePackage" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetParents" Member="AspNetParents">
    <Type Name="AspNetParent">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="AspNetParent_AspNetStudent" Member="AspNetStudents" ThisKey="Id" OtherKey="ParentId" Type="AspNetStudent" />
      <Association Name="AspNetUser_AspNetParent" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetReligions" Member="AspNetReligions">
    <Type Name="AspNetReligion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetReligion_AspNetEmployee" Member="AspNetEmployees" ThisKey="Id" OtherKey="ReligionId" Type="AspNetEmployee" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetSections" Member="AspNetSections">
    <Type Name="AspNetSection">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetSection_AspNetBranchClass_Section" Member="AspNetBranchClass_Sections" ThisKey="Id" OtherKey="SectionId" Type="AspNetBranchClass_Section" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetSessions" Member="AspNetSessions">
    <Type Name="AspNetSession">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Next" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AspNetSession_AspNetBranch_Class" Member="AspNetBranch_Classes" ThisKey="Id" OtherKey="SessionId" Type="AspNetBranch_Class" />
      <Association Name="AspNetSession_AspNetSession" Member="AspNetSessions" ThisKey="Id" OtherKey="Next" Type="AspNetSession" />
      <Association Name="AspNetSession_AspNetStudent_Enrollment" Member="AspNetStudent_Enrollments" ThisKey="Id" OtherKey="SessionId" Type="AspNetStudent_Enrollment" />
      <Association Name="AspNetSession_AspNetStudent_History" Member="AspNetStudent_Histories" ThisKey="Id" OtherKey="SessionId" Type="AspNetStudent_History" />
      <Association Name="AspNetSession_AspNetTeacher_Enrollment" Member="AspNetTeacher_Enrollments" ThisKey="Id" OtherKey="SessionId" Type="AspNetTeacher_Enrollment" />
      <Association Name="AspNetSession_AspNetTeacher_History" Member="AspNetTeacher_Histories" ThisKey="Id" OtherKey="SessionId" Type="AspNetTeacher_History" />
      <Association Name="AspNetSession_AspNetTerm" Member="AspNetTerms" ThisKey="Id" OtherKey="SessionId" Type="AspNetTerm" />
      <Association Name="AspNetSession_AspNetSession" Member="AspNetSession1" ThisKey="Next" OtherKey="Id" Type="AspNetSession" IsForeignKey="true" />
      <Association Name="AspNetStatus_AspNetSession" Member="AspNetStatus" ThisKey="StatusId" OtherKey="Id" Type="AspNetStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetStatus" Member="AspNetStatus">
    <Type Name="AspNetStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetStatus_AspNetSession" Member="AspNetSessions" ThisKey="Id" OtherKey="StatusId" Type="AspNetSession" />
      <Association Name="AspNetStatus_AspNetStudentAssessment" Member="AspNetStudentAssessments" ThisKey="Id" OtherKey="SubmissionStatusId" Type="AspNetStudentAssessment" />
      <Association Name="AspNetStatus_AspNetUser" Member="AspNetUsers" ThisKey="Id" OtherKey="StatusId" Type="AspNetUser" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetStudent_Enrollments" Member="AspNetStudent_Enrollments">
    <Type Name="AspNetStudent_Enrollment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AspNetStudent_Enrollment_AspNetStudentAssessment" Member="AspNetStudentAssessments" ThisKey="Id" OtherKey="StudentEnrollmentId" Type="AspNetStudentAssessment" />
      <Association Name="AspNetBranchClass_Section_AspNetStudent_Enrollment" Member="AspNetBranchClass_Section" ThisKey="SectionId" OtherKey="Id" Type="AspNetBranchClass_Section" IsForeignKey="true" />
      <Association Name="AspNetCourse_AspNetStudent_Enrollment" Member="AspNetCourse" ThisKey="CourseId" OtherKey="Id" Type="AspNetCourse" IsForeignKey="true" />
      <Association Name="AspNetSession_AspNetStudent_Enrollment" Member="AspNetSession" ThisKey="SessionId" OtherKey="Id" Type="AspNetSession" IsForeignKey="true" />
      <Association Name="AspNetStudent_AspNetStudent_Enrollment" Member="AspNetStudent" ThisKey="StudentId" OtherKey="Id" Type="AspNetStudent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetStudent_Histories" Member="AspNetStudent_Histories">
    <Type Name="AspNetStudent_History">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmissionStatusId" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AspNetCourse_AspNetStudent_History" Member="AspNetCourse" ThisKey="CourseId" OtherKey="Id" Type="AspNetCourse" IsForeignKey="true" />
      <Association Name="AspNetBranchClass_Section_AspNetStudent_History" Member="AspNetBranchClass_Section" ThisKey="SectionId" OtherKey="Id" Type="AspNetBranchClass_Section" IsForeignKey="true" />
      <Association Name="AspNetSession_AspNetStudent_History" Member="AspNetSession" ThisKey="SessionId" OtherKey="Id" Type="AspNetSession" IsForeignKey="true" />
      <Association Name="AspNetStudent_AspNetStudent_History" Member="AspNetStudent" ThisKey="StudentId" OtherKey="Id" Type="AspNetStudent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetStudentAssessments" Member="AspNetStudentAssessments">
    <Type Name="AspNetStudentAssessment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentEnrollmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObtainedMarks" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="SubmissionStatusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssessmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssessmmentSolutionFile" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetAssessment_AspNetStudentAssessment" Member="AspNetAssessment" ThisKey="AssessmentId" OtherKey="Id" Type="AspNetAssessment" IsForeignKey="true" />
      <Association Name="AspNetStatus_AspNetStudentAssessment" Member="AspNetStatus" ThisKey="SubmissionStatusId" OtherKey="Id" Type="AspNetStatus" IsForeignKey="true" />
      <Association Name="AspNetStudent_Enrollment_AspNetStudentAssessment" Member="AspNetStudent_Enrollment" ThisKey="StudentEnrollmentId" OtherKey="Id" Type="AspNetStudent_Enrollment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetStudents" Member="AspNetStudents">
    <Type Name="AspNetStudent">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="RollNo" Type="System.String" DbType="NVarChar(31) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="BranchId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="[File]" Member="File" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AspNetStudent_AspNetStudent_Enrollment" Member="AspNetStudent_Enrollments" ThisKey="Id" OtherKey="StudentId" Type="AspNetStudent_Enrollment" />
      <Association Name="AspNetStudent_AspNetStudent_History" Member="AspNetStudent_Histories" ThisKey="Id" OtherKey="StudentId" Type="AspNetStudent_History" />
      <Association Name="AspNetStudent_AspNetStudentSection" Member="AspNetStudentSections" ThisKey="Id" OtherKey="StudentId" Type="AspNetStudentSection" />
      <Association Name="AspNetBranch_AspNetStudent" Member="AspNetBranch" ThisKey="BranchId" OtherKey="Id" Type="AspNetBranch" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetParent_AspNetStudent" Member="AspNetParent" ThisKey="ParentId" OtherKey="Id" Type="AspNetParent" IsForeignKey="true" />
      <Association Name="AspNetUser_AspNetStudent" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetStudentSection" Member="AspNetStudentSections">
    <Type Name="AspNetStudentSection">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BranchClassSectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AspNetBranchClass_Section_AspNetStudentSection" Member="AspNetBranchClass_Section" ThisKey="BranchClassSectionId" OtherKey="Id" Type="AspNetBranchClass_Section" IsForeignKey="true" />
      <Association Name="AspNetStudent_AspNetStudentSection" Member="AspNetStudent" ThisKey="StudentId" OtherKey="Id" Type="AspNetStudent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetTeacher_Enrollments" Member="AspNetTeacher_Enrollments">
    <Type Name="AspNetTeacher_Enrollment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeacherId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AspNetCourse_AspNetTeacher_Enrollment" Member="AspNetCourse" ThisKey="CourseId" OtherKey="Id" Type="AspNetCourse" IsForeignKey="true" />
      <Association Name="AspNetBranchClass_Section_AspNetTeacher_Enrollment" Member="AspNetBranchClass_Section" ThisKey="SectionId" OtherKey="Id" Type="AspNetBranchClass_Section" IsForeignKey="true" />
      <Association Name="AspNetSession_AspNetTeacher_Enrollment" Member="AspNetSession" ThisKey="SessionId" OtherKey="Id" Type="AspNetSession" IsForeignKey="true" />
      <Association Name="AspNetTeacher_AspNetTeacher_Enrollment" Member="AspNetTeacher" ThisKey="TeacherId" OtherKey="Id" Type="AspNetTeacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetTeacher_Histories" Member="AspNetTeacher_Histories">
    <Type Name="AspNetTeacher_History">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeachertId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmissionStatusId" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AspNetCourse_AspNetTeacher_History" Member="AspNetCourse" ThisKey="CourseId" OtherKey="Id" Type="AspNetCourse" IsForeignKey="true" />
      <Association Name="AspNetBranchClass_Section_AspNetTeacher_History" Member="AspNetBranchClass_Section" ThisKey="SectionId" OtherKey="Id" Type="AspNetBranchClass_Section" IsForeignKey="true" />
      <Association Name="AspNetSession_AspNetTeacher_History" Member="AspNetSession" ThisKey="SessionId" OtherKey="Id" Type="AspNetSession" IsForeignKey="true" />
      <Association Name="AspNetTeacher_AspNetTeacher_History" Member="AspNetTeacher" ThisKey="TeachertId" OtherKey="Id" Type="AspNetTeacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetTeachers" Member="AspNetTeachers">
    <Type Name="AspNetTeacher">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationNo" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AspNetTeacher_AspNetTeacher_Enrollment" Member="AspNetTeacher_Enrollments" ThisKey="Id" OtherKey="TeacherId" Type="AspNetTeacher_Enrollment" />
      <Association Name="AspNetTeacher_AspNetTeacher_History" Member="AspNetTeacher_Histories" ThisKey="Id" OtherKey="TeachertId" Type="AspNetTeacher_History" />
      <Association Name="AspNetEmployee_AspNetTeacher" Member="AspNetEmployee" ThisKey="EmployeeId" OtherKey="Id" Type="AspNetEmployee" IsForeignKey="true" />
      <Association Name="AspNetUser_AspNetTeacher" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetTerms" Member="AspNetTerms">
    <Type Name="AspNetTerm">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="AspNetTerm_AspNetAssessment" Member="AspNetAssessments" ThisKey="Id" OtherKey="TermId" Type="AspNetAssessment" />
      <Association Name="AspNetSession_AspNetTerm" Member="AspNetSession" ThisKey="SessionId" OtherKey="Id" Type="AspNetSession" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetAccountant" Member="AspNetAccountants" ThisKey="Id" OtherKey="UserId" Type="AspNetAccountant" />
      <Association Name="AspNetUser_AspNetBranch_Admin" Member="AspNetBranch_Admins" ThisKey="Id" OtherKey="AdminId" Type="AspNetBranch_Admin" />
      <Association Name="AspNetUser_AspNetBranch" Member="AspNetBranches" ThisKey="Id" OtherKey="BranchPrincipalId" Type="AspNetBranch" />
      <Association Name="AspNetUser_AspNetDepartment" Member="AspNetDepartments" ThisKey="Id" OtherKey="HeadId" Type="AspNetDepartment" />
      <Association Name="AspNetUser_AspNetLog" Member="AspNetLogs" ThisKey="Id" OtherKey="UserId" Type="AspNetLog" />
      <Association Name="AspNetUser_AspNetParent" Member="AspNetParents" ThisKey="Id" OtherKey="UserId" Type="AspNetParent" />
      <Association Name="AspNetUser_AspNetStudent" Member="AspNetStudents" ThisKey="Id" OtherKey="UserId" Type="AspNetStudent" />
      <Association Name="AspNetUser_AspNetTeacher" Member="AspNetTeachers" ThisKey="Id" OtherKey="UserId" Type="AspNetTeacher" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
      <Association Name="AspNetStatus_AspNetUser" Member="AspNetStatus" ThisKey="StatusId" OtherKey="Id" Type="AspNetStatus" IsForeignKey="true" />
    </Type>
  </Table>
</Database>